 language: scala
 before_install:
   - "git clone https://github.com/wala/WALA.git"
   - "cd WALA"
   - "mvn clean install -DskipTests=true"
   - "cd .."
   - "wget http://repository.grepcode.com/java/ext/com/google/android/android/4.4.2_r1/android-4.4.2_r1.jar"
   - "cd lib && ./install_deps.sh"
   - cd ..
 scala:
   - "2.10.2"
 jdk:
   - openjdk7
